### ISSUE TITLE
Issue in admin/tickets

### ISSUE THREAD

**Issue by afshintalebi** [mb-programmer/startpoint#11]
تو بخش مدیریت، وقتی لینک تیکت ها رو کلیک می کنیم، از دیتا و قالب بخش پست ها استفاده میشه.

**Comment by mb-programmer** [comment]
Hello my friend.
It was added to the project by one of my college and I didn't check it completely
I am planning to change the way it work. I think this type of tickets is for advanced use and my purpose is to keep the project as simple as it gets.
